title: Ivan's IST Blog
author: Ivan Davila
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
My Blog Today will be about how IST is an important field in todays standards for schools and many jobs

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
